language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'

before_script:
  - phpenv config-rm xdebug.ini
  - composer install

env:
  - TASK=tests-unit
  - TASK=tests-examples
  - TASK=static-analysis

script: "composer $TASK"
